### ISSUE TITLE
Convert over to standard Python logging. We need to determine what and when to log.  I suggest we log errors, warnings and info of the running processes and not log data.

### ISSUE THREAD

**Issue by webbhm** [futureag/mvp#11]
Estimated Level of work: 2 Days.
Next Step: @webbhm to review what is in experimental and determine what changes would be made.
Priority: Medium

**Comment by futureagstl** [comment]
Notes from backlog grooming 6/7/18:

This is a system-wide change it touches quite a few different parts of the system. From a scheduling perspective, you have to plan this at a time it doesn't impact anything else.

Quite a bit of work to do.

Python logging has different capabilities and levels of detail. In the experimental branch, each module creates its own logger that tacks back onto the primary logger. You can put the module that is logging into the main log entry so you're aware of where it came from. We can add inheritance so it sets up a top-level logger with a defined format and then each other module can choose to follow. Things like intervals, the information logged, etc. can all be customized so what we need to do is really decide upon a standard.
