### ISSUE TITLE
Standardize python file naming and documentation (comments)

### ISSUE THREAD

**Issue by webbhm** [futureag/mvp#7]
Time Estimate: On-Going throughout development.
Priority: Medium

**Comment by futureagstl** [comment]
Notes from Backlog grooming 6/7/2018:

Python community already has some standards in place called "PEP" which they follow pretty rigorously. @ferguman will provide links to these and then we will decide upon and document our standard and implement as we continue to develop.

**Comment by ferguman** [comment]
PEP 8 is the one we should all read and adopt (or at least argue about :))
PEP 8 - https://www.python.org/dev/peps/pep-0008

A little more discipline and rigor are involved in moving beyond PEP 8 but here is one that details a standard for annotations:
Standard for Annotations- PEP 3107 - https://www.python.org/dev/peps/pep-3107

Some projects develop there own cheat sheets that pick out the stuff from PEP 8 or other standards that they want to live by.
